name: WuTaoDi
favicon: null
layout_spectrum: 0.9973
typography_spectrum: 0.25495
title: Wu-Tao-Di Academy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dadada'
    - '#b7b7b7'
    - '#434343'
    - '#7c7c7c'
    - '#2a1d14'
  brandStrength: 0.1875
  lightness: 0.5422090995125473
  saturation: 0.7597687167581171
  rhythmicContrast: 0.5528718172572553
purpose: []
